# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=board1!
      - MYSQL_DATABASE=board
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
